### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by TonyPS** [kzh-dev/pine-bot-client#1]
The server http://pine-api.kzh-crypto.net/ is not responding.  Is there anyway you can include a module to perform what this server is doing in pine-bot-client?

os.system("python pine-bot-client.py support bitflyer")
2019-04-02 22:59:59,383: CRITICAL: fail to execute 'support: Bad status code: <Response [502]>
Traceback (most recent call last):
  File "pine-bot-client.py", line 139, in <module>
    do_support(params, args[0], args[1])
  File "C:\Temp\NotKnowing\command\support.py", line 9, in do_support
    res = call_api(params, '/exchange-support', exchange=exchange, market=market)
  File "C:\Temp\NotKnowing\util\comm.py", line 23, in call_api
    _, json = _call_api(ap_params, path, **kws)
  File "C:\Temp\NotKnowing\util\comm.py", line 15, in _call_api
    raise BadResponse('Bad status code: {}'.format(r))
util.comm.BadResponse: Bad status code: <Response [502]>

**Comment by kzh-dev** [comment]
Sorry for the inconvenience. I stopped running the server.

So far I have no plan to release the server-side implementation for free.

**Comment by TonyPS** [comment]
How much cost for the server-side .py files?  Also do they work and
accurately convert the .pine to cctx?  Could you issue me a refund in case
the coversion doesn't work compared to side-by-side with TradingView
alerts?  I will be happy as long as my server alerts I can re-create with
your conversion software.  I will use it for trading only and I will not
pass it along to anyone or post it online either.  I searched everywhere
for a simple converter like you built and it doesn't seem to exist.  It is
the missing link for 'new python programmers' like me who don't know how to
read the cctx language.  So I am very much interested in paying for it.

For free could you do a test coversion for me of a .pine, so I can test
basic function of your software output??
